---
title: "models"
author: "Joe LaRocca"
date: "2025-03-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(corrplot)
library(caret)
library(glmnet)
```

## Upload Data (still need a relative path for this)

```{r}

load("./dat1.RData")
load("./dat2.RData")

```

## Specify Training and Testing Sets

```{r}

antibody_train = dat1
antibody_test = dat2

antibody_train = antibody_train |> select(-id)
antibody_test = antibody_test |> select(-id)

```

## OLS Model

```{r}

lm_antibody = lm(log_antibody ~ ., data = antibody_train)
summary(lm_antibody)

MSPE_lm_pred = predict(lm_antibody, newdata = antibody_test)

MSPE_lm = mean((MSE_lm_pred - antibody_test$log_antibody)^2)
MSPE_lm

```

## LASSO Model

```{r}

set.seed(2025)

ctrl = trainControl(method = "cv", number = 10)

antibody_lasso_fit = train(log_antibody ~ ., 
                          data = antibody_train,
                          method = "glmnet",
                          tuneGrid = expand.grid(
                            alpha = 1, 
                            lambda = exp(seq(6, -6, length = 100))
                          ),
                          trControl = ctrl)

plot(antibody_lasso_fit, xTrans = log)

antibody_lasso_pred = predict(antibody_lasso_fit, newdata = antibody_test |> select(-log_antibody))
MSPE_lasso = mean((antibody_lasso_pred - antibody_test$log_antibody)^2)
MSPE_lasso

```

## Elastic Net Model

```{r}

set.seed(2025)

antibody_enet_fit = train(log_antibody ~ ., 
                          data = antibody_train,
                          method = "glmnet",
                          tuneGrid = expand.grid(
                            alpha = seq(0, 0.95, length = 20), 
                            lambda = exp(seq(6, -6, length = 100))
                          ),
                          trControl = ctrl)


myCol = rainbow(25)
myPar = list(superpose.symbol = list(col = myCol),
             superpose.line = list(col = myCol))
plot(antibody_enet_fit, xTrans = log, par.settings = myPar)

antibody_enet_pred = predict(antibody_enet_fit, newdata = antibody_test |> select(-log_antibody))
MSPE_enet = mean((antibody_enet_pred - antibody_test$log_antibody)^2)
MSPE_enet

```




