---
title: "Appendix"
author: "Joe LaRocca, Brooklynn McNeil, Malika Top"
date: "2025-03-31"
output: pdf_document
header-includes:
  - \usepackage{float}
  - \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(ISLR)
library(glmnet)
library(caret)
library(pls)
library(tidymodels)
library(corrplot)
library(ggplot2)
library(plotmo)
library(ggrepel)
library(dplyr)
library(pdp)
library(patchwork)
library(gtsummary)
library(flextable)
```



```{r data_load}
load("./dat1.RData")
load("./dat2.RData")
# split dat1 into a train and test dataset

dat1 = dat1 |> 
  dplyr::select(-id) |> 
  mutate(gender = factor(gender, levels = c(0, 1), labels = c("female", "male")),
         race = factor(race, levels = c(1, 2, 3, 4), labels = c("white", "asian", 
                                                                "black", "hispanic")),
         smoking = factor(smoking, levels = c(0, 1, 2), labels = c("never_smoked",
                                                                   "former_smoker",
                                                                   "current_smoker")),
         diabetes = factor(diabetes, levels = c(0, 1), labels = c("no", "yes")),
         hypertension = factor(hypertension, levels = c(0, 1), labels = c("no", "yes")))

#colSums(is.na(dat1))
train_df = dat1 
test_df = dat2 |> dplyr::select(-id)
```


```{r sum_stats}
cont_pred = c("age", "height", "weight", "bmi", "SBP", "LDL", "time")
cat_pred = c("gender", "race", "smoking", "diabetes", "hypertension")
# Table 1
cat_table = dat1 |> 
  tbl_summary(include = c(gender, race, smoking, diabetes, hypertension)) |> 
  modify_caption("Table 1. Patient Categorical Characteristics")|> 
  bold_labels()
cat_table |> as_flex_table()
# Table 2
cont_table = dat1 |> 
  tbl_summary(include = c(age, height, weight, bmi, SBP, LDL, time),
              type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c("{median} ({p25}, {p75})",
                                              "{min}, {max}")
              ) |> 
  modify_caption("Table 2. Patient Continuous Characteristics") |> 
  bold_labels()
cont_table |> as_flex_table()
# Table 3
outcome_table = dat1 |> 
  tbl_summary(include = log_antibody,
              type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c("{median} ({p25}, {p75})",
                                              "{min}, {max}")) |> 
  modify_caption("Table 3. Log-Antibody Level Characteristics") |> 
  bold_labels()
outcome_table|> as_flex_table()
```

```{r response_dist}

pdf(
  here::here("Figures/figure_1.pdf"),
  width = 10,
  height = 7
  )

# Fig. 1
dat1 |>
  ggplot(aes(x = log_antibody)) +
  geom_histogram() +
  ggtitle("Distribution of log-transformed antibody levels") +
  labs(caption = "The distribution of the response variable is Normal so no transformations need to be applied." ,
       x = "Log Antibody Levels",
       y = "Frequency") 

dev.off()

```

```{r pred_dist}

pdf(
  here::here("Figures/figure_2.pdf"),
  width = 10,
  height = 7
  )

# Fig. 2
barplots = list()
for (pred in cat_pred) {
  plot = ggplot(dat1, aes(x = .data[[pred]], fill = .data[[pred]])) +
  geom_bar() +
  labs(title = paste("Distribution of", pred)) +
  theme(plot.title = element_text(size = 10, hjust = 0.5, margin = margin(b = 10)),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 8),
        axis.text=element_text(size=8))
  barplots[[pred]] = plot
}

wrap_plots(barplots) + plot_annotation(title = "Figure 2")

dev.off()
```


```{r histograms}

pdf(
  here::here("Figures/figure_3.pdf"),
  width = 10,
  height = 7
  )

# Fig. 3
histograms = list()
for (pred in cont_pred) {
  plot = ggplot(dat1, aes(x = .data[[pred]])) +
  geom_histogram() +
  labs(title = paste("Distribution of", pred)) +
  theme(plot.title = element_text(size = 10, hjust = 0.5, margin = margin(b = 10)),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 8),
        axis.text=element_text(size=8))
  histograms[[pred]] = plot
}

wrap_plots(histograms) 

dev.off()

```
 


```{r boxplots}

pdf(
  here::here("Figures/figure_4.pdf"),
  width = 10,
  height = 7
  )

# Fig. 4
boxplots = list()
for (pred in cat_pred) {
  plot = ggplot(dat1, aes(x = .data[[pred]], y = log_antibody, fill = .data[[pred]])) +
  geom_boxplot() +
  theme(plot.title = element_text(size = 10, hjust = 0.5, margin = margin(b = 10)),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 8),
        axis.text=element_text(size=8))
  boxplots[[pred]] = plot
}
wrap_plots(boxplots) 

dev.off()
```

```{r scatterplots}

pdf(
  here::here("Figures/figure_5.pdf"),
  width = 10,
  height = 7
  )

# Fig. 5
scatter_plots = list()
for (pred in cont_pred) {
  plot = ggplot(dat1, aes(x = .data[[pred]], y = log_antibody)) +
  geom_point() +
  geom_smooth() +
  labs(y = "Log Antibody Levels") + 
  theme(plot.title = element_text(size = 10, hjust = 0.5),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 8),
        axis.text=element_text(size=8))
  scatter_plots[[pred]] = plot
}
wrap_plots(scatter_plots) 

dev.off()

```

```{r corrplots, fig.width=6, fig.height=6}

pdf(
  here::here("Figures/figure_6.pdf"),
  width = 10,
  height = 7
  )

# Fig. 6
x = model.matrix(log_antibody ~ ., dat1)[,-1]
y = dat1$log_antibody
corrplot::corrplot(cor(x), method = "circle", type = "full")

dev.off()

```


#### Elastic Net
```{r enet}
ctrl1 = trainControl(method = "cv", number = 10)
set.seed(2025)
enet_fit = train(log_antibody ~ .,
               data = train_df,
               method = "glmnet",
               trControl = ctrl1,
               tuneGrid = expand.grid(alpha = seq(0,1, length = 21), # create a model for each alpha value with 0.5 spacing
                                      lambda = exp(seq(-10,0, length = 100)))) # create gride for 100 different lambda values between -10, 0

# find the lambda value with lowest RMSE
myCol = rainbow(25)
myPar = list(superpose.symbol = list(col = myCol),
             superpose.line = list(col = myCol))

# Fig. 7
plot(enet_fit, par.settings = myPar, xTrans = log, main = "Figure 7")
```

#### PLS
```{r pls}
set.seed(2025)

pls_fit = train(log_antibody ~ .,
               data = train_df,
               method = "pls",
               trControl = ctrl1,
               tuneLength = 15,
               preProcess = c("center", "scale")) 
summary(pls_fit)
pls_plot = ggplot(pls_fit, highlight = TRUE) + ggtitle("Figure 8: Optimal number of components")
pls_plot 
pls_fit$bestTune # = 9
```

#### GAM
```{r gam}
set.seed(2025)
gam_fit = train(log_antibody ~ .,
               data = train_df,
               method = "gam",
               trControl = ctrl1)
summary(gam_fit)
gam_fit$finalModel
```

#### MARS
```{r mars}

pdf(
  here::here("Figures/figure_7.pdf"),
  width = 10,
  height = 7
  )

set.seed(56)

mars_grid <- expand.grid(degree = 1:3,nprune = 2:15)

mars_fit = train(log_antibody ~ .,
               data = train_df,
               method = "earth",
               tuneGrid = mars_grid,
               trControl = ctrl1)
ggplot(mars_fit) 

dev.off()

```
#### Linear regression
```{r ols}
set.seed(56)
lm_fit = train(log_antibody ~ .,
               data = train_df,
               method = "lm",
               trControl = ctrl1)
  
# get the coefficients
summary(lm_fit)
```

#### CV RMSEs

```{r resamps}

pdf(
  here::here("Figures/figure_8.pdf"),
  width = 10,
  height = 7
  )

set.seed(56)
resamp = resamples(list(
  lm = lm_fit,
  enet = enet_fit,
  pls = pls_fit,
  gam = gam_fit,
  mars = mars_fit
))

bwplot(resamp, metric = "RMSE") 

dev.off()

```

```{r}

pdf(
  here::here("Figures/figure_9.pdf"),
  width = 10,
  height = 7
  )

set.seed(56)
resamp = resamples(list(
  lm = lm_fit,
  enet = enet_fit,
  pls = pls_fit,
  gam = gam_fit,
  mars = mars_fit
))

parallelplot(resamp, metric = "RMSE")

dev.off()

```


#### Test RMSE

```{r}

MSPE_mars_pred = predict(mars_fit, newdata = test_df)
MSPE_mars = mean((MSPE_mars_pred - test_df$log_antibody)^2)
RMSPE_mars = sqrt(MSPE_mars)
RMSPE_mars

```

